### PR TITLE
Add libs to platformio.ini to make install easier

### PR DESCRIPTION
**Pull request by chron0**
thx for sharing!

### CODE REVIEW

**Comment by oe3cjb** [comment]
hi, das wirft bei mir beim compilieren einige Fehlermeldungen aus - hast Du eine Idee?
Interessanterweise passiert dies nicht bei allen Libs!?

Compiling .pio\build\heltec_wifi_lora_32\lib988\Adafruit SSD1306_ID135\Adafruit_SSD1306.cpp.o
Archiving .pio\build\heltec_wifi_lora_32\lib4e5\libAdafruit Unified Sensor_ID31.a

Compiling .pio\build\heltec_wifi_lora_32\libe21\AXP202X_Library\axp20x.cpp.o
Archiving .pio\build\heltec_wifi_lora_32\libf29\libTinyGPSPlus_ID1655.a
xtensa-esp32-elf-ar: .pio\build\heltec_wifi_lora_32\libf29\libTinyGPSPlus_ID1655.a: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\libf29\libTinyGPSPlus_ID1655.a] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\lib37f\Adafruit GFX Library_ID13\Adafruit_SPITFT.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\lib37f\Adafruit GFX Library_ID13\Adafruit_SPITFT.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\lib5ae\Wire\Wire.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\lib5ae\Wire\Wire.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\lib37f\Adafruit GFX Library_ID13\Adafruit_GFX.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\lib37f\Adafruit GFX Library_ID13\Adafruit_GFX.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\src\TTGO_T-Beam_LoRa_APRS.ino.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\src\TTGO_T-Beam_LoRa_APRS.ino.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\lib988\Adafruit SSD1306_ID135\Adafruit_SSD1306.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\lib988\Adafruit SSD1306_ID135\Adafruit_SSD1306.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio\build\heltec_wifi_lora_32\libe21\AXP202X_Library\axp20x.cpp.o: No such file or directory
*** [.pio\build\heltec_wifi_lora_32\libe21\AXP202X_Library\axp20x.cpp.o] Error 1

**Comment by oe3cjb** [comment]
alles retour - beim zweiten mal compilieren hat es geklappt

**Review by oe3cjb — APPROVED** [review]
tks es 73

**Comment by chron0** [comment]
unklar, haengt moeglicherweise auch mit dem board type zusammen. Es gibt mittlerweile auch explizit t-beam in platformio, d.h. der heltec umweg ist nicht mehr zwingend.

**Pull request merged**
